// ─────────────────────────────────────────────────────────────
// DATA — sem se přidávají další slovesa
// present: 6 tvarů bez zájmena (je, tu, il, nous, vous, ils)
// aux: "avoir" | "etre" (pomocné sloveso v passé composé)
// pp: příčestí minulé
// grp: "reg" = pravidelné; bez grp = nepravidelné
// ─────────────────────────────────────────────────────────────
const VERBS = [
  // ── Page 1 ──
  { inf: "être", cz: "být", present: ["suis", "es", "est", "sommes", "êtes", "sont"], pp: "été", aux: "avoir" },
  { inf: "avoir", cz: "mít", present: ["ai", "as", "a", "avons", "avez", "ont"], pp: "eu", aux: "avoir" },
  { inf: "faire", cz: "dělat", present: ["fais", "fais", "fait", "faisons", "faites", "font"], pp: "fait", aux: "avoir" },
  { inf: "dire", cz: "říct", present: ["dis", "dis", "dit", "disons", "dites", "disent"], pp: "dit", aux: "avoir" },
  { inf: "pouvoir", cz: "moct", present: ["peux", "peux", "peut", "pouvons", "pouvez", "peuvent"], pp: "pu", aux: "avoir" },
  { inf: "aller", cz: "jít, jet", present: ["vais", "vas", "va", "allons", "allez", "vont"], pp: "allé", aux: "etre" },
  // ── Page 2 ──
  { inf: "voir", cz: "vidět", present: ["vois", "vois", "voit", "voyons", "voyez", "voient"], pp: "vu", aux: "avoir" },
  { inf: "vouloir", cz: "chtít", present: ["veux", "veux", "veut", "voulons", "voulez", "veulent"], pp: "voulu", aux: "avoir" },
  { inf: "venir", cz: "přijít", present: ["viens", "viens", "vient", "venons", "venez", "viennent"], pp: "venu", aux: "etre" },
  { inf: "devenir", cz: "stát se", present: ["deviens", "deviens", "devient", "devenons", "devenez", "deviennent"], pp: "devenu", aux: "etre" },
  { inf: "tenir", cz: "držet", present: ["tiens", "tiens", "tient", "tenons", "tenez", "tiennent"], pp: "tenu", aux: "avoir" },
  { inf: "revenir", cz: "vrátit se", present: ["reviens", "reviens", "revient", "revenons", "revenez", "reviennent"], pp: "revenu", aux: "etre" },
  { inf: "devoir", cz: "muset (dlužit)", present: ["dois", "dois", "doit", "devons", "devez", "doivent"], pp: "dû", aux: "avoir" },
  { inf: "prendre", cz: "vzít", present: ["prends", "prends", "prend", "prenons", "prenez", "prennent"], pp: "pris", aux: "avoir" },
  { inf: "apprendre", cz: "učit se", present: ["apprends", "apprends", "apprend", "apprenons", "apprenez", "apprennent"], pp: "appris", aux: "avoir" },
  { inf: "comprendre", cz: "pochopit", present: ["comprends", "comprends", "comprend", "comprenons", "comprenez", "comprennent"], pp: "compris", aux: "avoir" },
  { inf: "reprendre", cz: "znovu vzít", present: ["reprends", "reprends", "reprend", "reprenons", "reprenez", "reprennent"], pp: "repris", aux: "avoir" },
  { inf: "mettre", cz: "dát, položit, obléct", present: ["mets", "mets", "met", "mettons", "mettez", "mettent"], pp: "mis", aux: "avoir" },
  { inf: "permettre", cz: "povolit", present: ["permets", "permets", "permet", "permettons", "permettez", "permettent"], pp: "permis", aux: "avoir" },
  { inf: "remettre", cz: "vrátit, odložit", present: ["remets", "remets", "remet", "remettons", "remettez", "remettent"], pp: "remis", aux: "avoir" },
  { inf: "promettre", cz: "slíbit", present: ["promets", "promets", "promet", "promettons", "promettez", "promettent"], pp: "promis", aux: "avoir" },
  // ── Page 3 ──
  { inf: "savoir", cz: "vědět, umět", present: ["sais", "sais", "sait", "savons", "savez", "savent"], pp: "su", aux: "avoir" },
  { inf: "croire", cz: "věřit, myslet si", present: ["crois", "crois", "croit", "croyons", "croyez", "croient"], pp: "cru", aux: "avoir" },
  { inf: "répondre", cz: "odpovědět", present: ["réponds", "réponds", "répond", "répondons", "répondez", "répondent"], pp: "répondu", aux: "avoir" },
  { inf: "entendre", cz: "slyšet", present: ["entends", "entends", "entend", "entendons", "entendez", "entendent"], pp: "entendu", aux: "avoir" },
  { inf: "rendre", cz: "vrátit (něco)", present: ["rends", "rends", "rend", "rendons", "rendez", "rendent"], pp: "rendu", aux: "avoir" },
  { inf: "attendre", cz: "čekat", present: ["attends", "attends", "attend", "attendons", "attendez", "attendent"], pp: "attendu", aux: "avoir" },
  { inf: "perdre", cz: "ztratit", present: ["perds", "perds", "perd", "perdons", "perdez", "perdent"], pp: "perdu", aux: "avoir" },
  { inf: "descendre", cz: "sejít, sestoupit", present: ["descends", "descends", "descend", "descendons", "descendez", "descendent"], pp: "descendu", aux: "etre" },
  { inf: "tendre", cz: "natáhnout, podat", present: ["tends", "tends", "tend", "tendons", "tendez", "tendent"], pp: "tendu", aux: "avoir" },
  { inf: "connaître", cz: "znát", present: ["connais", "connais", "connaît", "connaissons", "connaissez", "connaissent"], pp: "connu", aux: "avoir" },
  { inf: "paraître", cz: "zdát se, vypadat", present: ["parais", "parais", "paraît", "paraissons", "paraissez", "paraissent"], pp: "paru", aux: "avoir" },
  { inf: "reconnaître", cz: "poznat", present: ["reconnais", "reconnais", "reconnaît", "reconnaissons", "reconnaissez", "reconnaissent"], pp: "reconnu", aux: "avoir" },
  { inf: "disparaître", cz: "zmizet", present: ["disparais", "disparais", "disparaît", "disparaissons", "disparaissez", "disparaissent"], pp: "disparu", aux: "avoir" },
  { inf: "apparaître", cz: "objevit se", present: ["apparais", "apparais", "apparaît", "apparaissons", "apparaissez", "apparaissent"], pp: "apparu", aux: "etre" },
  { inf: "sentir", cz: "cítit", present: ["sens", "sens", "sent", "sentons", "sentez", "sentent"], pp: "senti", aux: "avoir" },
  { inf: "sortir", cz: "jít ven, vyjít", present: ["sors", "sors", "sort", "sortons", "sortez", "sortent"], pp: "sorti", aux: "etre" },
  { inf: "partir", cz: "odjet, odejít", present: ["pars", "pars", "part", "partons", "partez", "partent"], pp: "parti", aux: "etre" },
  { inf: "vivre", cz: "žít", present: ["vis", "vis", "vit", "vivons", "vivez", "vivent"], pp: "vécu", aux: "avoir" },
  // ── Další nepravidelná slovesa ──
  { inf: "lire", cz: "číst", present: ["lis", "lis", "lit", "lisons", "lisez", "lisent"], pp: "lu", aux: "avoir" },
  { inf: "écrire", cz: "psát", present: ["écris", "écris", "écrit", "écrivons", "écrivez", "écrivent"], pp: "écrit", aux: "avoir" },
  { inf: "boire", cz: "pít", present: ["bois", "bois", "boit", "buvons", "buvez", "boivent"], pp: "bu", aux: "avoir" },
  { inf: "recevoir", cz: "dostat, obdržet", present: ["reçois", "reçois", "reçoit", "recevons", "recevez", "reçoivent"], pp: "reçu", aux: "avoir" },
  { inf: "conduire", cz: "řídit", present: ["conduis", "conduis", "conduit", "conduisons", "conduisez", "conduisent"], pp: "conduit", aux: "avoir" },
  { inf: "traduire", cz: "přeložit", present: ["traduis", "traduis", "traduit", "traduisons", "traduisez", "traduisent"], pp: "traduit", aux: "avoir" },
  { inf: "construire", cz: "postavit", present: ["construis", "construis", "construit", "construisons", "construisez", "construisent"], pp: "construit", aux: "avoir" },
  { inf: "ouvrir", cz: "otevřít", present: ["ouvre", "ouvres", "ouvre", "ouvrons", "ouvrez", "ouvrent"], pp: "ouvert", aux: "avoir" },
  { inf: "offrir", cz: "darovat, nabídnout", present: ["offre", "offres", "offre", "offrons", "offrez", "offrent"], pp: "offert", aux: "avoir" },
  { inf: "découvrir", cz: "objevit", present: ["découvre", "découvres", "découvre", "découvrons", "découvrez", "découvrent"], pp: "découvert", aux: "avoir" },
  { inf: "dormir", cz: "spát", present: ["dors", "dors", "dort", "dormons", "dormez", "dorment"], pp: "dormi", aux: "avoir" },
  { inf: "servir", cz: "obsluhovat, podávat", present: ["sers", "sers", "sert", "servons", "servez", "servent"], pp: "servi", aux: "avoir" },
  { inf: "mentir", cz: "lhát", present: ["mens", "mens", "ment", "mentons", "mentez", "mentent"], pp: "menti", aux: "avoir" },
  { inf: "courir", cz: "běžet", present: ["cours", "cours", "court", "courons", "courez", "courent"], pp: "couru", aux: "avoir" },
  { inf: "mourir", cz: "zemřít", present: ["meurs", "meurs", "meurt", "mourons", "mourez", "meurent"], pp: "mort", aux: "etre" },
  { inf: "naître", cz: "narodit se", present: ["nais", "nais", "naît", "naissons", "naissez", "naissent"], pp: "né", aux: "etre" },
  { inf: "rire", cz: "smát se", present: ["ris", "ris", "rit", "rions", "riez", "rient"], pp: "ri", aux: "avoir" },
  { inf: "sourire", cz: "usmívat se", present: ["souris", "souris", "sourit", "sourions", "souriez", "sourient"], pp: "souri", aux: "avoir" },
  { inf: "suivre", cz: "sledovat, následovat", present: ["suis", "suis", "suit", "suivons", "suivez", "suivent"], pp: "suivi", aux: "avoir" },
  { inf: "battre", cz: "bít, tlouct", present: ["bats", "bats", "bat", "battons", "battez", "battent"], pp: "battu", aux: "avoir" },
  { inf: "craindre", cz: "obávat se", present: ["crains", "crains", "craint", "craignons", "craignez", "craignent"], pp: "craint", aux: "avoir" },
  { inf: "peindre", cz: "malovat", present: ["peins", "peins", "peint", "peignons", "peignez", "peignent"], pp: "peint", aux: "avoir" },
  { inf: "éteindre", cz: "zhasnout, vypnout", present: ["éteins", "éteins", "éteint", "éteignons", "éteignez", "éteignent"], pp: "éteint", aux: "avoir" },
  { inf: "rejoindre", cz: "připojit se k", present: ["rejoins", "rejoins", "rejoint", "rejoignons", "rejoignez", "rejoignent"], pp: "rejoint", aux: "avoir" },
  { inf: "plaire", cz: "líbit se", present: ["plais", "plais", "plaît", "plaisons", "plaisez", "plaisent"], pp: "plu", aux: "avoir" },
  { inf: "envoyer", cz: "poslat", present: ["envoie", "envoies", "envoie", "envoyons", "envoyez", "envoient"], pp: "envoyé", aux: "avoir" },
  // ── Pravidelná slovesa (-er) ──
  { inf: "parler", cz: "mluvit", grp: "reg", present: ["parle", "parles", "parle", "parlons", "parlez", "parlent"], pp: "parlé", aux: "avoir" },
  { inf: "habiter", cz: "bydlet", grp: "reg", present: ["habite", "habites", "habite", "habitons", "habitez", "habitent"], pp: "habité", aux: "avoir" },
  { inf: "travailler", cz: "pracovat", grp: "reg", present: ["travaille", "travailles", "travaille", "travaillons", "travaillez", "travaillent"], pp: "travaillé", aux: "avoir" },
  { inf: "aimer", cz: "mít rád, milovat", grp: "reg", present: ["aime", "aimes", "aime", "aimons", "aimez", "aiment"], pp: "aimé", aux: "avoir" },
  { inf: "manger", cz: "jíst", grp: "reg", present: ["mange", "manges", "mange", "mangeons", "mangez", "mangent"], pp: "mangé", aux: "avoir" },
  { inf: "commencer", cz: "začít", grp: "reg", present: ["commence", "commences", "commence", "commençons", "commencez", "commencent"], pp: "commencé", aux: "avoir" },
  { inf: "acheter", cz: "koupit", grp: "reg", present: ["achète", "achètes", "achète", "achetons", "achetez", "achètent"], pp: "acheté", aux: "avoir" },
  { inf: "préférer", cz: "dávat přednost", grp: "reg", present: ["préfère", "préfères", "préfère", "préférons", "préférez", "préfèrent"], pp: "préféré", aux: "avoir" },
  { inf: "appeler", cz: "volat, jmenovat", grp: "reg", present: ["appelle", "appelles", "appelle", "appelons", "appelez", "appellent"], pp: "appelé", aux: "avoir" },
  { inf: "jouer", cz: "hrát", grp: "reg", present: ["joue", "joues", "joue", "jouons", "jouez", "jouent"], pp: "joué", aux: "avoir" },
  { inf: "regarder", cz: "dívat se", grp: "reg", present: ["regarde", "regardes", "regarde", "regardons", "regardez", "regardent"], pp: "regardé", aux: "avoir" },
  { inf: "écouter", cz: "poslouchat", grp: "reg", present: ["écoute", "écoutes", "écoute", "écoutons", "écoutez", "écoutent"], pp: "écouté", aux: "avoir" },
  { inf: "donner", cz: "dávat", grp: "reg", present: ["donne", "donnes", "donne", "donnons", "donnez", "donnent"], pp: "donné", aux: "avoir" },
  { inf: "penser", cz: "myslet (si)", grp: "reg", present: ["pense", "penses", "pense", "pensons", "pensez", "pensent"], pp: "pensé", aux: "avoir" },
  { inf: "trouver", cz: "najít", grp: "reg", present: ["trouve", "trouves", "trouve", "trouvons", "trouvez", "trouvent"], pp: "trouvé", aux: "avoir" },
  { inf: "chercher", cz: "hledat", grp: "reg", present: ["cherche", "cherches", "cherche", "cherchons", "cherchez", "cherchent"], pp: "cherché", aux: "avoir" },
  { inf: "demander", cz: "ptát se, žádat", grp: "reg", present: ["demande", "demandes", "demande", "demandons", "demandez", "demandent"], pp: "demandé", aux: "avoir" },
  { inf: "payer", cz: "platit", grp: "reg", present: ["paie", "paies", "paie", "payons", "payez", "paient"], pp: "payé", aux: "avoir" },
  // ── Pravidelná -er s être ──
  { inf: "arriver", cz: "přijet, dorazit", grp: "reg", present: ["arrive", "arrives", "arrive", "arrivons", "arrivez", "arrivent"], pp: "arrivé", aux: "etre" },
  { inf: "rester", cz: "zůstat", grp: "reg", present: ["reste", "restes", "reste", "restons", "restez", "restent"], pp: "resté", aux: "etre" },
  { inf: "tomber", cz: "spadnout", grp: "reg", present: ["tombe", "tombes", "tombe", "tombons", "tombez", "tombent"], pp: "tombé", aux: "etre" },
  { inf: "entrer", cz: "vstoupit", grp: "reg", present: ["entre", "entres", "entre", "entrons", "entrez", "entrent"], pp: "entré", aux: "etre" },
  { inf: "monter", cz: "vyjít nahoru, nastoupit", grp: "reg", present: ["monte", "montes", "monte", "montons", "montez", "montent"], pp: "monté", aux: "etre" },
  { inf: "rentrer", cz: "vrátit se domů", grp: "reg", present: ["rentre", "rentres", "rentre", "rentrons", "rentrez", "rentrent"], pp: "rentré", aux: "etre" },
  // ── Pravidelná -ir a -re ──
  { inf: "finir", cz: "skončit, dokončit", grp: "reg", present: ["finis", "finis", "finit", "finissons", "finissez", "finissent"], pp: "fini", aux: "avoir" },
  { inf: "choisir", cz: "vybrat", grp: "reg", present: ["choisis", "choisis", "choisit", "choisissons", "choisissez", "choisissent"], pp: "choisi", aux: "avoir" },
  { inf: "réussir", cz: "uspět", grp: "reg", present: ["réussis", "réussis", "réussit", "réussissons", "réussissez", "réussissent"], pp: "réussi", aux: "avoir" },
  { inf: "grandir", cz: "vyrůst, růst", grp: "reg", present: ["grandis", "grandis", "grandit", "grandissons", "grandissez", "grandissent"], pp: "grandi", aux: "avoir" },
  { inf: "vendre", cz: "prodat", grp: "reg", present: ["vends", "vends", "vend", "vendons", "vendez", "vendent"], pp: "vendu", aux: "avoir" },
];
